name: Permit Service - Promote TEST

on:
  workflow_dispatch:

env:
  ORIG_TAG: dev
  PROMOTE_TAG: test
  IMAGE: permits

jobs:
  promote-image:
    name: promote-image
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Openshift image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Promote from dev to test
        run: |
          docker tag ${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}/${{ secrets.ARTIFACTORY_PROJECT_NAME }}/${{ env.IMAGE }}:${{ env.ORIG_TAG }} ${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}/${{ secrets.ARTIFACTORY_PROJECT_NAME }}/${{ env.IMAGE }}:${{ env.PROMOTE_TAG }}
          docker push ${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}/${{ secrets.ARTIFACTORY_PROJECT_NAME }}/${{ env.IMAGE }}:${{ env.PROMOTE_TAG }}
  trigger-gitops:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: promote-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git Ops Push
        run: ./gitops/commit.sh ${{ env.IMAGE }} dev test ${{ github.actor }} ${{ secrets.GH_TOKEN }}
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.7"
      - name: Setup ArgoCD CLI
        uses: imajeetyadav/argocd-cli@v1
        with:
          version: v2.7.9 # optional
      - name: oc login
        run: oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
      - name: Notification
        run: ./gitops/watch-deployment.sh permits test ${{ github.sha }} ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK }} ${{ secrets.ARGOCD_SERVER }} ${{ secrets.ARGO_CD_CLI_JWT }}

  run-if-failed:
    runs-on: ubuntu-latest
    needs: [trigger-gitops]
    if: failure()
    steps:
      - name: Notification
        run: ./gitops/notify_discord.sh permits test ${{ github.sha }} ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK }} 1
